<?php

namespace Database\Seeders;

use App\Models\BitacoraCategoria;
use Illuminate\Database\Seeder;

class BitacoraCategoriaSeeder extends Seeder
{
    public function run(): void
    {
        $categorias = [
            // ['codigo' => 'llamada', 'nombre' => 'Llamada telefónica', 'descripcion' => 'Registro de llamadas telefónicas con clientes o terceros'],
            // ['codigo' => 'correo', 'nombre' => 'Correo electrónico', 'descripcion' => 'Registro de correos electrónicos enviados o recibidos'],
            // ['codigo' => 'reunion', 'nombre' => 'Reunión con cliente', 'descripcion' => 'Registro de reuniones presenciales o virtuales con clientes'],
            // ['codigo' => 'documento', 'nombre' => 'Preparación de documento', 'descripcion' => 'Registro de preparación o revisión de documentos'],
            // ['codigo' => 'audiencia', 'nombre' => 'Audiencia', 'descripcion' => 'Registro de audiencias o comparecencias'],
            // ['codigo' => 'investigacion', 'nombre' => 'Investigación', 'descripcion' => 'Registro de investigaciones o búsquedas de información'],
            // ['codigo' => 'pago', 'nombre' => 'Registro de pago', 'descripcion' => 'Registro de pagos realizados o recibidos'],
            // ['codigo' => 'otro', 'nombre' => 'Otro', 'descripcion' => 'Otras actividades no categorizadas'],
            ['codigo' => 'ouverture', 'nombre' => 'OUVERTURE', 'descripcion' => 'Apertura de expediente'],
    ['codigo' => 'fermeture', 'nombre' => 'FERMETURE', 'descripcion' => 'Cierre de expediente'],
    ['codigo' => 'archive_docs_client', 'nombre' => 'ARCHIVE DOCUMENTS DU CLIENT', 'descripcion' => 'Archivo de documentos del cliente'],
    ['codigo' => 'archive_communications', 'nombre' => 'ARCHIVE COMMUNICATIONS', 'descripcion' => 'Archivo de comunicaciones'],
    ['codigo' => 'archive_comm_cisr', 'nombre' => 'ARCHIVE COMMUNICATIONS COMISSION IMMIGRATION (CISR)', 'descripcion' => 'Archivo de comunicaciones con la Comisión de Inmigración'],
    ['codigo' => 'archive_comm_asfc', 'nombre' => 'ARCHIVE COMMUNICATIONS ASFC', 'descripcion' => 'Archivo de comunicaciones con ASFC'],
    ['codigo' => 'archive_comm_ministere', 'nombre' => 'ARCHIVE COMMUNICATIONS MINISTèRE', 'descripcion' => 'Archivo de comunicaciones con el Ministerio'],
    ['codigo' => 'archive_comm_du_client', 'nombre' => 'ARCHIVE COMMUNICATIONS DU CLIENT', 'descripcion' => 'Archivo de comunicaciones del cliente'],
    ['codigo' => 'archive_comm_au_client', 'nombre' => 'ARCHIVE COMMUNICATIONS AU CLIENT', 'descripcion' => 'Archivo de comunicaciones al cliente'],
    ['codigo' => 'archive_preuves', 'nombre' => 'ARCHIVE PREUVES', 'descripcion' => 'Archivo de pruebas'],
    ['codigo' => 'archive_notes', 'nombre' => 'ARCHIVE NOTES AU DOSSIER', 'descripcion' => 'Archivo de notas al expediente'],
    ['codigo' => 'traduction_docs', 'nombre' => 'TRADUCTION DES DOCUMENTS', 'descripcion' => 'Traducción de documentos'],
    ['codigo' => 'remplir_formulaires', 'nombre' => 'REMPLIR FORMULAIRES', 'descripcion' => 'Completar formularios'],
    ['codigo' => 'mise_a_jour_formulaires', 'nombre' => 'MISE à JOUR FORMULAIRES', 'descripcion' => 'Actualización de formularios'],
    ['codigo' => 'archive_fda', 'nombre' => 'ARCHIVE FDA', 'descripcion' => 'Archivo FDA'],
    ['codigo' => 'archive_soumissions', 'nombre' => 'ARCHIVE SOUMISSIONS', 'descripcion' => 'Archivo de presentaciones'],
    ['codigo' => 'archive_da', 'nombre' => 'ARCHIVE DA', 'descripcion' => 'Archivo DA'],
    ['codigo' => 'archive', 'nombre' => 'ARCHIVE', 'descripcion' => 'Archivo general'],
    ['codigo' => 'appel_au_client', 'nombre' => 'APPEL AU CLIENT', 'descripcion' => 'Llamada al cliente'],
    ['codigo' => 'appel_du_client', 'nombre' => 'APPEL DU CLIENT', 'descripcion' => 'Llamada del cliente'],
    ['codigo' => 'appel_au_cour', 'nombre' => 'APPEL AU COUR', 'descripcion' => 'Llamada a la corte'],
    ['codigo' => 'appel_du_cour', 'nombre' => 'APPEL DU COUR', 'descripcion' => 'Llamada de la corte'],
    ['codigo' => 'appel_au_asfc', 'nombre' => 'APPEL AU ASFC', 'descripcion' => 'Llamada a ASFC'],
    ['codigo' => 'appel_du_asfc', 'nombre' => 'APPEL DU ASFC', 'descripcion' => 'Llamada de ASFC'],
    ['codigo' => 'appel_au_ministere', 'nombre' => 'APPEL AU MINISTèRE', 'descripcion' => 'Llamada al Ministerio'],
    ['codigo' => 'appel_du_ministere', 'nombre' => 'APPEL DU MINISTèRE', 'descripcion' => 'Llamada del Ministerio'],
    ['codigo' => 'appel_a_la_commission', 'nombre' => 'APPEL à LA COMMISSION', 'descripcion' => 'Llamada a la Comisión'],
    ['codigo' => 'appel_du_comission', 'nombre' => 'APPEL DU COMISSION', 'descripcion' => 'Llamada de la Comisión'],
    ['codigo' => 'appel_au_spr', 'nombre' => 'APPEL AU SPR', 'descripcion' => 'Llamada al SPR'],
    ['codigo' => 'appel_du_spr', 'nombre' => 'APPEL DU SPR', 'descripcion' => 'Llamada del SPR'],
    ['codigo' => 'changement_adresse', 'nombre' => 'CHANGEMENT D\'ADRESSE', 'descripcion' => 'Cambio de dirección'],
    ['codigo' => 'changement_adresse_spr', 'nombre' => 'CHANGEMENT D\'ADRESSE SPR', 'descripcion' => 'Cambio de dirección SPR'],
    ['codigo' => 'changement_adresse_sar', 'nombre' => 'CHANGEMENT D\'ADRESSE SAR', 'descripcion' => 'Cambio de dirección SAR'],
    ['codigo' => 'frais_psychologue', 'nombre' => 'FRAIS DE PSYCHOLOGUE ENVOYÉ A AJ', 'descripcion' => 'Gastos de psicólogo enviados a AJ'],
    ['codigo' => 'avis_reception_csq', 'nombre' => 'AVIS DE RÉCEPTION REÇU DU CSQ', 'descripcion' => 'Aviso de recepción recibido del CSQ'],
    ['codigo' => 'permis_travail', 'nombre' => 'PERMIS DE TRAVAIL', 'descripcion' => 'Permiso de trabajo'],
    ['codigo' => 'revision', 'nombre' => 'RÉVISION', 'descripcion' => 'Revisión'],
    ['codigo' => 'autre', 'nombre' => 'AUTRE', 'descripcion' => 'Otro'],
    ['codigo' => 'courriel', 'nombre' => 'COURRIEL', 'descripcion' => 'Correo electrónico'],
    ['codigo' => 'verification', 'nombre' => 'VÉRIFICATION', 'descripcion' => 'Verificación'],
    ['codigo' => 'changement_avocate', 'nombre' => 'CHANGEMENT AVOCATE', 'descripcion' => 'Cambio de abogado'],
    ['codigo' => 'analyse', 'nombre' => 'ANALYSE', 'descripcion' => 'Análisis'],
    ['codigo' => 'envoi_copie_dossier', 'nombre' => 'ENVOI COPIE DU DOSSIER éLECTRONIQUE', 'descripcion' => 'Envío de copia del expediente electrónico'],
    ['codigo' => 'reponse_courriel', 'nombre' => 'RéPONSE COURRIEL', 'descripcion' => 'Respuesta a correo electrónico'],
    ['codigo' => 'redaction_courriel', 'nombre' => 'RéDACTION COURRIEL', 'descripcion' => 'Redacción de correo electrónico'],
    ['codigo' => 'depot_electronique', 'nombre' => 'DéPôT éLECTRONIQUE', 'descripcion' => 'Depósito electrónico'],
    ['codigo' => 'depot_fax', 'nombre' => 'DéPôT PAR FAX', 'descripcion' => 'Depósito por fax'],
    ['codigo' => 'depot', 'nombre' => 'DéPôT', 'descripcion' => 'Depósito'],
    ['codigo' => 'depot_cisr', 'nombre' => 'DéPôT COMISSION IMMIGRATION (CISR)', 'descripcion' => 'Depósito en la Comisión de Inmigración'],
    ['codigo' => 'depot_cour', 'nombre' => 'DéPôT COUR', 'descripcion' => 'Depósito en la corte'],
    ['codigo' => 'paiement_recu', 'nombre' => 'PAIEMENT REÇU', 'descripcion' => 'Pago recibido'],
    ['codigo' => 'renouvellement', 'nombre' => 'RENOUVELLEMENT', 'descripcion' => 'Renovación'],
    ['codigo' => 'lecture_dossier', 'nombre' => 'LECTURE DU DOSSIER', 'descripcion' => 'Lectura del expediente'],
    ['codigo' => 'preparation_plaidoirie', 'nombre' => 'PRéPARATION PLAIDOIRIE', 'descripcion' => 'Preparación de alegato'],
    ['codigo' => 'audience_virtuelle', 'nombre' => 'AUDIENCE VIRTUELLE', 'descripcion' => 'Audiencia virtual'],
    ['codigo' => 'audience', 'nombre' => 'AUDIENCE', 'descripcion' => 'Audiencia'],
    ['codigo' => 'revision_preuves', 'nombre' => 'RÉVISION DE PREUVES', 'descripcion' => 'Revisión de pruebas'],
    ['codigo' => 'photocopies', 'nombre' => 'PHOTOCOPIES', 'descripcion' => 'Fotocopias'],
    ['codigo' => 'scan', 'nombre' => 'SCAN / NUMéRISATION', 'descripcion' => 'Escaneo / Digitalización'],
    ['codigo' => 'etude_dossier', 'nombre' => 'ETUDE DU DOSSIER', 'descripcion' => 'Estudio del expediente'],
    ['codigo' => 'fax_recu', 'nombre' => 'FAX REçU', 'descripcion' => 'Fax recibido'],
    ['codigo' => 'fax_recu_rdv', 'nombre' => 'FAX REçU RDV AIDE JURIDIQUE', 'descripcion' => 'Fax recibido de cita de ayuda jurídica'],
    ['codigo' => 'fax_recu_decision', 'nombre' => 'FAX REçU AVIS DÉCISION', 'descripcion' => 'Fax recibido de aviso de decisión'],
    ['codigo' => 'fax_recu_comparution', 'nombre' => 'FAX REçU AVIS COMPARUTION', 'descripcion' => 'Fax recibido de aviso de comparecencia'],
    ['codigo' => 'appel_fournisseur', 'nombre' => 'APPEL AU FOURNISSEUR', 'descripcion' => 'Llamada al proveedor'],
    ['codigo' => 'accompagnement', 'nombre' => 'ACCOMPAGNEMENT', 'descripcion' => 'Acompañamiento'],
    ['codigo' => 'creation_dossier_ligne', 'nombre' => 'CRéATION DU DOSSIER EN LIGNE', 'descripcion' => 'Creación del expediente en línea'],
    ['codigo' => 'mise_a_jour_ligne', 'nombre' => 'MISE à JOUR INFORMATION EN LIGNE', 'descripcion' => 'Actualización de información en línea'],
    ['codigo' => 'chercher_dossier', 'nombre' => 'CHERCHER DOSSIER', 'descripcion' => 'Buscar expediente'],
    ['codigo' => 'archivage_physique', 'nombre' => 'ARCHIVAGE PHYSIQUE DOSSIER', 'descripcion' => 'Archivo físico del expediente'],
    ['codigo' => 'archivage_digital_lettre', 'nombre' => 'ARCHIVAGE DIGITAL LETTRE', 'descripcion' => 'Archivo digital de carta'],
    ['codigo' => 'archivage_notes', 'nombre' => 'ARCHIVAGE NOTES DOSSIER', 'descripcion' => 'Archivo de notas del expediente'],
    ['codigo' => 'creation_dossier_physique', 'nombre' => 'CRÉATION DOSSIER PHYSIQUE', 'descripcion' => 'Creación de expediente físico'],
    ['codigo' => 'numerisation_archivage', 'nombre' => 'NUMERISATION ET ARCHIVAGE DIGITAL LETTRE', 'descripcion' => 'Digitalización y archivo digital de carta'],
    ['codigo' => 'archivage_physique_lettre', 'nombre' => 'ARCHIVAGE PHYSIQUE LETTRE', 'descripcion' => 'Archivo físico de carta'],
    ['codigo' => 'chercher_info_formulaires', 'nombre' => 'CHERCHER INFORMATION ET REMPLIR FORMULAIRES', 'descripcion' => 'Buscar información y completar formularios'],
    ['codigo' => 'interpretation', 'nombre' => 'INTERPRETATION', 'descripcion' => 'Interpretación'],
    ['codigo' => 'traduction', 'nombre' => 'TRADUCTION', 'descripcion' => 'Traducción'],
    ['codigo' => 'revision_correction', 'nombre' => 'RÉVISION ET CORRECTION', 'descripcion' => 'Revisión y corrección'],
    ['codigo' => 'revision_courriel', 'nombre' => 'RéVISION COURRIEL ET RESEAUX SOCIAUX', 'descripcion' => 'Revisión de correo electrónico y redes sociales'],
    ['codigo' => 'frais_expertise_fax', 'nombre' => 'FRAIS D\'EXPERTISE ENVOYÉ PAR FAX', 'descripcion' => 'Gastos de peritaje enviados por fax'],
    ['codigo' => 'archivage_lettre_simple', 'nombre' => 'ARCHIVAGE PHYSIQUE LETTRE DEMANDES MOINS COMPLEXES', 'descripcion' => 'Archivo físico de carta para solicitudes menos complejas'],
    ['codigo' => 'archivage_lettre_decision', 'nombre' => 'ARCHIVAGE PHYSIQUE LETTRE AVIS DE DÉCISION', 'descripcion' => 'Archivo físico de carta de aviso de decisión'],
    ['codigo' => 'archivage_lettre_convocation', 'nombre' => 'ARCHIVAGE PHYSIQUE LETTRE CONVOCATION AUDIENCE', 'descripcion' => 'Archivo físico de carta de convocatoria a audiencia'],
    ['codigo' => 'preparation_audience', 'nombre' => 'PRéPARATION AUDIENCE', 'descripcion' => 'Preparación de audiencia'],
    ['codigo' => 'entretien_client', 'nombre' => 'ENTRETIEN AVEC LE CLIENT', 'descripcion' => 'Entrevista con el cliente'],
    ['codigo' => 'facturation_aide', 'nombre' => 'FACTURATION AIDE JURIDIQUE', 'descripcion' => 'Facturación de ayuda jurídica'],
    ['codigo' => 'facturation_client', 'nombre' => 'FACTURATION CLIENT', 'descripcion' => 'Facturación al cliente'],
    ['codigo' => 'preparation_soumissions', 'nombre' => 'PRÉPARATION SOUMISSIONS ÉCRITES', 'descripcion' => 'Preparación de presentaciones escritas'],
    ['codigo' => 'ecoute_enregistrement', 'nombre' => 'ECOUTE DE L\'ENREGISTREMENT D\'AUDIENCE', 'descripcion' => 'Escucha de la grabación de audiencia'],
    ['codigo' => 'etudes_preuves', 'nombre' => 'ETUDES DES PREUVES', 'descripcion' => 'Estudio de pruebas'],
    ['codigo' => 'preparation_preuves', 'nombre' => 'PRéPARATION DE PREUVES', 'descripcion' => 'Preparación de pruebas'],
    ['codigo' => 'envoi_document', 'nombre' => 'ENVOI DOCUMENT', 'descripcion' => 'Envío de documento'],
    ['codigo' => 'recu_document', 'nombre' => 'REÇU DOCUMENT', 'descripcion' => 'Recepción de documento'],
    ['codigo' => 'archivage_physique_general', 'nombre' => 'ARCHIVAGE PHYSIQUE', 'descripcion' => 'Archivo físico general'],
    ['codigo' => 'archivage_digital', 'nombre' => 'ARCHIVAGE DIGITAL', 'descripcion' => 'Archivo digital'],
    ['codigo' => 'envoi_preuves_traduction', 'nombre' => 'ENVOI DE PREUVES À TRADUCTION', 'descripcion' => 'Envío de pruebas para traducción'],
    ['codigo' => 'redaction_arguments', 'nombre' => 'REDACTION DES ARGUMENTS', 'descripcion' => 'Redacción de argumentos'],
    ['codigo' => 'envoi_poste', 'nombre' => 'ENVOI PAR LA POSTE ET NUMéRO DE SUIVI', 'descripcion' => 'Envío por correo postal y número de seguimiento'],
    ['codigo' => 'consultation', 'nombre' => 'CONSULTATION', 'descripcion' => 'Consulta'],
    ['codigo' => 'premiere_rencontre', 'nombre' => '1èRE RENCONTRE', 'descripcion' => 'Primera reunión'],
        ];

        foreach ($categorias as $categoria) {
            BitacoraCategoria::create([
                'codigo' => $categoria['codigo'],
                'nombre' => $categoria['nombre'],
                'descripcion' => $categoria['descripcion'],
                'activo' => true,
            ]);
        }
    }
}

